#ifndef ESDL_DELTATIMEDEFS_H
#define ESDL_DELTATIMEDEFS_H

/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    esdl_deltaTimeDefs
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for delta time calculation
 *
 **/

/**
 * Esta variavel global contem o valor deltaT escalonado da tarefa em execucao.
 * O codigo gerado para o modelo ASCET usa esta variavel diretamente para acessar esse valor.
 **/
#define ASCET_DELTA_T_SCALED_TYPE float32
extern ASCET_DELTA_T_SCALED_TYPE ASD_DT_SCALED;

/**
 * Macro definition to set the global ASD_DT_SCALED variable
 * The provided rawDt argument is expected to be an expression representing the deltaT in seconds
 **/
#define ASCET_SET_MODEL_DT(rawDt) ASD_DT_SCALED = (rawDt)

#endif /* ESDL_DELTATIMEDEFS_H */
