/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_PID_Controler_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    22/11/2020 03:54:55
*
* @brief   "components_PID_Controler>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_PID_Controler_Automatic.h"
#include "global_Throtle_Interface_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_PID_Controler_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_PID_Controler'
 * data set:.....................................'COMPONENTS_PID_CONTROLER_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const volatile struct components_PID_Controler_Automatic_CAL_MEM_SUBSTRUCT components_PID_Controler_CAL_MEM = {
   /* struct element:'components_PID_Controler_CAL_MEM.Error_Gain' */
   1.0F,
   /* struct element:'components_PID_Controler_CAL_MEM.Kd' */
   0.0F,
   /* struct element:'components_PID_Controler_CAL_MEM.Kp' */
   1.0F,
   /* struct element:'components_PID_Controler_CAL_MEM.PID_Saturation' */
   4095.0F,
   /* substruct: components_PID_Controler_CAL_MEM.Integrator_instance */
   {
      /* struct element:'components_PID_Controler_CAL_MEM.Integrator_instance.Integrator_Forced' */
      0.0F,
      /* struct element:'components_PID_Controler_CAL_MEM.Integrator_instance.Integrator_Max' */
      2.0F,
      /* struct element:'components_PID_Controler_CAL_MEM.Integrator_instance.Integrator_Min' */
      -2.0F,
      /* struct element:'components_PID_Controler_CAL_MEM.Integrator_instance.Ki' */
      0.5F,
      /* struct element:'components_PID_Controler_CAL_MEM.Integrator_instance.Integrator_Ignore' */
      false,
      /* struct element:'components_PID_Controler_CAL_MEM.Integrator_instance.Integrator_Reset' */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_PID_Controler_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_PID_Controler_RAM'
 * ---------------------------------------------------------------------------*/
struct components_PID_Controler_Automatic_RAM_SUBSTRUCT components_PID_Controler_RAM = {
   /* struct element:'components_PID_Controler_RAM.Actual_Position' */
   0.0F,
   /* struct element:'components_PID_Controler_RAM.Desired_Position' */
   0.0F,
   /* struct element:'components_PID_Controler_RAM.PID_Result' */
   0.0F,
   /* substruct: components_PID_Controler_RAM.Integrator_instance */
   {
      /* struct element:'components_PID_Controler_RAM.Integrator_instance.Int_Buffer' */
      0.0F,
      /* struct element:'components_PID_Controler_RAM.Integrator_instance.Int_Error_Input' */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_PID_Controler_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_PID_Controler'
 * ---------------------------------------------------------------------------*/
const struct components_PID_Controler_Automatic components_PID_Controler = {
   /* substruct: components_PID_Controler.Integrator_instance */
   {
      /* type descriptor pointer 'components_Integrator_Automatic_CAL_MEM' para memory class CAL_MEM */
      &components_PID_Controler_CAL_MEM.Integrator_instance,
      /* type descriptor pointer 'components_Integrator_Automatic_RAM' para memory class RAM */
      &components_PID_Controler_RAM.Integrator_instance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_PID_Controler'
 ******************************************************************************/


#define Actual_Position_VAL (components_PID_Controler_RAM.Actual_Position)
#define Desired_Position_VAL (components_PID_Controler_RAM.Desired_Position)
#define Error_Gain_VAL (components_PID_Controler_CAL_MEM.Error_Gain)
#define Integrator_instance_REF (&(components_PID_Controler.Integrator_instance))
#define Kd_VAL (components_PID_Controler_CAL_MEM.Kd)
#define Kp_VAL (components_PID_Controler_CAL_MEM.Kp)
#define PID_Result_VAL (components_PID_Controler_RAM.PID_Result)
#define PID_Saturation_VAL (components_PID_Controler_CAL_MEM.PID_Saturation)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_PID_Controler_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void components_PID_Controler_Automatic_calc (void)
{
   /* temp. variables */
   float32 _t1real32;

   /* define local message copies */
   float32 global_Throtle_Interface_PID_error__components_PID_Controler_Automatic_calc;
   float32 global_Throtle_Interface_PID_in__components_PID_Controler_Automatic_calc;
   float32 global_Throtle_Interface_PID_out__components_PID_Controler_Automatic_calc;
   /* receive messages implicitly */
   {
      DisableAllInterrupts();
      global_Throtle_Interface_PID_error__components_PID_Controler_Automatic_calc = global_Throtle_Interface_PID_error;
      global_Throtle_Interface_PID_in__components_PID_Controler_Automatic_calc = global_Throtle_Interface_PID_in;
      global_Throtle_Interface_PID_out__components_PID_Controler_Automatic_calc = global_Throtle_Interface_PID_out;
      EnableAllInterrupts();
   }
   _t1real32
      = (Desired_Position_VAL - Actual_Position_VAL) * Error_Gain_VAL;
   _t1real32
      = components_Integrator_Automatic_Integrator_Arg(Integrator_instance_REF, _t1real32, 0.01F) + (_t1real32 * Kd_VAL * 100.0F) + (_t1real32 * Kp_VAL);
   _t1real32
      = ((_t1real32 >= -PID_Saturation_VAL) ? _t1real32 : -PID_Saturation_VAL);
   PID_Result_VAL
      = ((_t1real32 <= PID_Saturation_VAL) ? _t1real32 : PID_Saturation_VAL);
   global_Throtle_Interface_PID_out__components_PID_Controler_Automatic_calc = PID_Result_VAL;
   Desired_Position_VAL
      = global_Throtle_Interface_PID_in__components_PID_Controler_Automatic_calc;
   Actual_Position_VAL
      = global_Throtle_Interface_PID_error__components_PID_Controler_Automatic_calc;
   /* send messages implicitly */
   {
      global_Throtle_Interface_PID_out = global_Throtle_Interface_PID_out__components_PID_Controler_Automatic_calc;
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_PID_Controler_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/


