#ifndef _ASD_COMPONENTS_PID_CONTROLER_AUTOMATIC_H_
#define _ASD_COMPONENTS_PID_CONTROLER_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_PID_Controler_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    22/11/2020 03:54:55
*
* @brief   "components_PID_Controler>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_Integrator_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_PID_Controler_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_PID_Controler_Automatic_CAL_MEM_SUBSTRUCT {
   float32 Error_Gain;
   float32 Kd;
   float32 Kp;
   float32 PID_Saturation;
   struct components_Integrator_Automatic_CAL_MEM_SUBSTRUCT Integrator_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_PID_Controler_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_PID_Controler_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_PID_Controler_Automatic_RAM_SUBSTRUCT {
   float32 Actual_Position;
   float32 Desired_Position;
   float32 PID_Result;
   struct components_Integrator_Automatic_RAM_SUBSTRUCT Integrator_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_PID_Controler_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_PID_Controler_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_PID_Controler_Automatic {
   struct components_Integrator_Automatic Integrator_instance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_PID_Controler_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........components_PID_Controler_Automatic */
#define _components_PID_Controler_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_PID_Controler_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern const volatile struct components_PID_Controler_Automatic_CAL_MEM_SUBSTRUCT components_PID_Controler_CAL_MEM;

/* forward declaration of substruct variable 'components_PID_Controler_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_PID_Controler_Automatic_RAM_SUBSTRUCT components_PID_Controler_RAM;

/* forward declaration of component variable 'components_PID_Controler' */
/* containing 'ROM' memory class tree */
extern const struct components_PID_Controler_Automatic components_PID_Controler;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_PID_Controler_Automatic
 ******************************************************************************/
extern void components_PID_Controler_Automatic_calc (void);



#endif /* _ASD_COMPONENTS_PID_CONTROLER_AUTOMATIC_H_ */
