#ifndef _ASD_COMPONENTS_INTEGRATOR_AUTOMATIC_H_
#define _ASD_COMPONENTS_INTEGRATOR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Integrator_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    22/11/2020 03:54:55
*
* @brief   "components_Integrator>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_Integrator_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_Integrator_Automatic_CAL_MEM_SUBSTRUCT {
   float32 Integrator_Forced;
   float32 Integrator_Max;
   float32 Integrator_Min;
   float32 Ki;
   uint8 Integrator_Ignore;
   uint8 Integrator_Reset;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_Integrator_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_Integrator_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_Integrator_Automatic_RAM_SUBSTRUCT {
   float32 Int_Buffer;
   float32 Int_Error_Input;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_Integrator_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_Integrator_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_Integrator_Automatic {
   const volatile struct components_Integrator_Automatic_CAL_MEM_SUBSTRUCT * components_Integrator_Automatic_CAL_MEM;
   struct components_Integrator_Automatic_RAM_SUBSTRUCT * components_Integrator_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_Integrator_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............components_Integrator_Automatic */
#define _components_Integrator_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_Integrator_Automatic
 ******************************************************************************/
extern float32 components_Integrator_Automatic_Integrator_Arg (
               const struct components_Integrator_Automatic * self,
   /* IN    */ const float32                                  arg,
   /* IN    */ const float32                                  dT_Val
   );



#endif /* _ASD_COMPONENTS_INTEGRATOR_AUTOMATIC_H_ */
