/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Integrator_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    22/11/2020 03:54:55
*
* @brief   "components_Integrator>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Integrator_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define Int_Buffer_VAL (self->components_Integrator_Automatic_RAM->Int_Buffer)
#define Int_Error_Input_VAL (self->components_Integrator_Automatic_RAM->Int_Error_Input)
#define Integrator_Ignore_VAL (self->components_Integrator_Automatic_CAL_MEM->Integrator_Ignore)
#define Integrator_Reset_VAL (self->components_Integrator_Automatic_CAL_MEM->Integrator_Reset)
#define Ki_VAL (self->components_Integrator_Automatic_CAL_MEM->Ki)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Integrator_Automatic_Integrator_Arg'
 * ----------------------------------------------------------------------------
 * model name:...................................'Integrator_Arg'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Integrator_Automatic_Integrator_Arg (
               const struct components_Integrator_Automatic * self,
   /* IN    */ const float32                                  arg,
   /* IN    */ const float32                                  dT_Val
   )
{
   Int_Buffer_VAL = (Int_Error_Input_VAL * Ki_VAL * dT_Val) + Int_Buffer_VAL;
   if (Integrator_Reset_VAL)
   {
      Int_Buffer_VAL = 0.0F;
   } /* end if */
   if (Integrator_Ignore_VAL)
   {
      Int_Buffer_VAL = arg;
   } /* end if */
   Int_Error_Input_VAL = arg;
   return Int_Buffer_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Integrator_Automatic_Integrator_Arg'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/


