#ifndef ESDL_MESSAGECOPY_H
#define ESDL_MESSAGECOPY_H

/**
  * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @file    esdl_messageCopy.h
  *
  * @author  Generated by ASCET-DEVELOPER V7.4.1
  *
  * @date    11/22/2020 4:54:55 AM
  *
  * @brief   Header file for message copy logic
  **/



#endif /* ESDL_MESSAGECOPY_H */
