#ifndef _ASD_GLOBAL_THROTLE_INTERFACE_AUTOMATIC_H_
#define _ASD_GLOBAL_THROTLE_INTERFACE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    global_Throtle_Interface_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    22/11/2020 03:54:55
*
* @brief   "global_Throtle_Interface>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module GLOBAL_THROTLE_INTERFACE_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .........global_Throtle_Interface_Automatic */
#define _global_Throtle_Interface_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module global_Throtle_Interface_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 global_Throtle_Interface_PID_error;
extern float32 global_Throtle_Interface_PID_in;
extern float32 global_Throtle_Interface_PID_out;


#endif /* _ASD_GLOBAL_THROTLE_INTERFACE_AUTOMATIC_H_ */
