/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    global_Throtle_Interface_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    22/11/2020 03:54:55
*
* @brief   "global_Throtle_Interface>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "global_Throtle_Interface_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'global_Throtle_Interface'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/


/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................12
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'global_Throtle_Interface_PID_error' */
float32 global_Throtle_Interface_PID_error = 0.0F;
/* modelled as 'global_Throtle_Interface_PID_in' */
float32 global_Throtle_Interface_PID_in = 0.0F;
/* modelled as 'global_Throtle_Interface_PID_out' */
float32 global_Throtle_Interface_PID_out = 0.0F;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/


