#ifndef GLOBALH_H
#define GLOBALH_H
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    globalH.h
 *
 * @author  Generated by ASCET-DEVELOPER V7.4.1
 *
 * @date    22.11.2020 04:11:55
 *
 * @brief   este arquivo de cabecalho global suporta o recurso de pre-compiled header
 *
 **/
#include "esdl.h"
#endif /* GLOBALH_H */
