/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    ShutdownHook
 *
 * @author  Generated by ASCET
 *
 * @brief   implementacao de ShutdownHook
 *
 **/


/* BEGIN ShutdownHook with scheduling: - */
void ShutdownHook()
{
    /* no method calls defined */
}
/* END ShutdownHook */
