/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    StartupHook
 *
 * @author  Generated by ASCET
 *
 * @brief   implementacao de StartupHook
 *
 **/


/* BEGIN StartupHook with scheduling: - */
void StartupHook()
{
    /* no method calls defined */
}
/* END StartupHook */
