/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    Task0
 *
 * @author  Generated by ASCET
 *
 * @brief   Implementacao de Task0 - bare-metal (sem RTAOS)
 *          Refatorado: dependencias iLLD removidas, substituidas por MCAL API
 *
 * Alteracoes de refatoracao (migracao iLLD -> MCAL):
 *   - Removido: IfxPort.h           -> substituido por Dio.h (MCAL)
 *   - Removido: GPT12_Timer_Interrupt.h -> substituido por Gpt.h (MCAL)
 *   - Removido: hal_adc_inputs.h    -> substituido por Adc.h (MCAL)
 *   - Removido: hal_discrete_outputs.h -> substituido por Dio.h (MCAL)
 *   - Removidos: ADC_Background_Scan.h, CCU6_PWM_Generation.h, GTM_ATOM_PWM.h
 *     (drivers iLLD de baixo nivel, substituidos pelo MCAL)
 *
 **/
#include <stdbool.h>
#include "platform_defs.h"

/* MCAL API - substitui IfxPort, hal_discrete_outputs, hal_adc_inputs */
#include "Dio.h"
#include "Adc.h"

/* MCAL API - substitui GPT12_Timer_Interrupt */
#include "Gpt.h"

#include "rte_environment.h"
#include "rte_components.h"
#include "cdd_injectors.h"
#include "cdd_spark.h"
#include "cdd_fuelpump.h"

#include "tbi_interface.h"
#include "mngmt_interface.h"
#include "spark_interface.h"
#include "fuel_interface.h"
#include "tbi_setpoint_interface.h"

#include "cdd_synchronism.h"

#include "ECU_State_interface.h"

#include "xcp_can_if.h"
#include "XcpBasic.h"

volatile uint8 dbg_Task0_toggle = 0;

/******************************************************************************
 * BEGIN: DEFINITION OF TASK 'Task0' (bare-metal, periodo 10ms)
 * ---------------------------------------------------------------------------*/
void Task0_Run(void)
{
    dbg_Task0_toggle ^= 1U;

    /* XCP: Poll CAN RX/TX no inicio da tarefa */
    XcpCanIf_Handler();

    unsigned char ignition_on = Get8u_RTE_b_IgnitionOn();
    unsigned short int engine_rpm = Get16u_RTE_rpm_EngineSpeeed();
    (void)ignition_on;
    (void)engine_rpm;

    Update_RTE_EnvironmentSignals();
    Update_RTE_ComponentsSignals();

    ECU_State_Task_10ms();

    /* Controle da bomba de combustivel */
    CDD_FuelPump_Event();

    /* SOFTWARE COMPONENTS ASW */
    TBI_MainTask10ms();
    THROTTLE_MainTask10ms();

#if (TESTADVANCES_ENABLED == TRUE)
    CDD_SYNC_TestAdvancesSweepTask();
#endif

    /* XCP: Dispara evento DAQ canal 0 (10ms) apos todos os sinais atualizados */
    XcpEvent(0);
    /* XCP: Processamento em background (calculo de checksum) */
    XcpBackground();
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF TASK 'Task0'
 ******************************************************************************/
