#ifndef _ASD_THROTLE_PID_AUTOMATIC_H_
#define _ASD_THROTLE_PID_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    Throtle_PID_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.1 (Backend: Code Generator V7.4.0)
*
* @date    22/11/2020 03:54:55
*
* @brief   "Throtle_PID>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_PID_Controler_Automatic.h"
#include "global_Throtle_Interface_Automatic.h"


/* component structure for project THROTLE_PID_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......................Throtle_PID_Automatic */
#define _Throtle_PID_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project Throtle_PID_Automatic
 ******************************************************************************/



#endif /* _ASD_THROTLE_PID_AUTOMATIC_H_ */
